CE-742
bcgov/nr-compliance-enforcement-cm pull request #67
Opened 2024-06-19 20:10 UTC by gregorylavery

Modifies the display order and inserts the new 'Less lethal' entry into the right alphabetical place in the listing.
# Description

Please provide a summary of the change and the issue fixed. Please include relevant context. List dependency changes.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have already been accepted and merged

## Further comments

2024-06-19 22:01 UTC, afwilcox requested changes
Ah bad news @gregorylavery - I don't think there is anything wrong with your scripts, however when I run it the Less Lethal item is at the top.   I suspect the problem is in HwcrOutcomeCodeService.findAll.   This probably needs some sort of order by added to it.

2024-06-19 23:45 UTC, gregorylavery commented
I can see that problem now, from a process point of view would that be a new bug or can it just be handled here with a re-submit of the PR? I ask just because the UI code is quite different to the SQL changes... @afwilcox

2024-06-19 23:48 UTC, afwilcox commented
@gregorylavery  - you can just make the change in this PR.

2024-06-20 19:12 UTC, afwilcox approved these changes

2024-06-20 19:12 UTC, merged