Feat/ce 1002
bcgov/nr-compliance-enforcement-cm pull request #84
Opened 2024-09-11 23:54 UTC by marqueone-ps

# Description

Please provide a summary of the change and the issue fixed. Please include relevant context. List dependency changes.

Story # CE-1002

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have already been accepted and merged

## Further comments

2024-09-12 16:29 UTC, afwilcox requested changes

2024-09-12 16:29 UTC, afwilcox commented on migrations/sql/V1.23.0__CE-1002.sql
File should be named 1.27 as per convention (1.<sprint number>.0_<description>

Tables and Columns should all have comments.

2024-09-12 18:35 UTC, marqueone-ps commented on migrations/sql/V1.23.0__CE-1002.sql
renamed to use sprint number convention, and added comments to tables

2024-09-13 00:04 UTC, afwilcox submitted a review, later dismissed

2024-09-13 00:04 UTC, afwilcox commented on migrations/sql/V1.27.0__CE-1002.sql
> +COMMENT on table public.site_h is 'History table for site table';
I think these need to be case_management not public (same with the authorization permit history)

2024-09-13 02:34 UTC, afwilcox approved these changes

2024-09-13 02:35 UTC, merged